import { useState } from 'react'
import { Search, ShieldCheck } from 'lucide-react'
import WorkspaceShell from '../../components/workspace/WorkspaceShell'
import { EmptyState, Panel } from '../../components/workspace/WorkspaceUi'
import { semanticSearch } from '../../lib/api'

export default function ComplianceWorkspace() {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const submit = async event => { event.preventDefault(); if (!query.trim()) return; setLoading(true); setError(''); try { const data = await semanticSearch(query, 10, 'regulation'); setResults(data.results || []) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <WorkspaceShell title="Compliance scan" eyebrow="Regulatory evidence coverage"><div className="mx-auto max-w-5xl"><Panel className="p-5"><form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="compliance-query">Process or requirement</label><textarea id="compliance-query" value={query} onChange={event => setQuery(event.target.value)} rows={2} placeholder="Describe the procedure, requirement, or risk you need to validate…" className="min-h-20 flex-1 resize-none rounded-lg border border-[#fff9e8]/12 bg-[#1a180b] px-3 py-2 text-sm outline-none placeholder:text-[#8e876e] focus:border-[#ffbe0b]" /><button disabled={loading || !query.trim()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#ffbe0b] px-5 text-sm font-bold text-[#181609] hover:bg-[#ffda62] disabled:opacity-40"><Search size={16} />{loading ? 'Scanning' : 'Run scan'}</button></form></Panel>{error && <p className="mt-4 rounded-lg border border-rose-300/20 bg-rose-300/10 p-3 text-sm text-rose-200">{error}</p>}<div className="mt-5">{results === null ? <EmptyState title="Scan your regulation corpus" body="Once regulation documents are ingested, OnBrain ranks the evidence most relevant to your process or requirement." /> : results.length === 0 ? <EmptyState title="No regulation evidence found" body="Upload regulation documents first, or describe the requirement with more specific terms." /> : <div className="space-y-3">{results.map((result, index) => <Panel key={result.chunk_id || index} className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck size={16} className="text-emerald-300" />{result.source_filename || 'Regulation source'}</div><span className="rounded-full bg-[#ffbe0b]/10 px-2.5 py-1 text-[10px] font-bold text-[#ffda62]">{Math.round((result.relevance_score || 0) * 100)}% match</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#c7bea1]">{result.text}</p><p className="mt-3 text-[11px] text-[#8e876e]">Page {result.page_number || 1} · {result.doc_type?.replace('_', ' ')}</p></Panel>)}</div>}</div></div></WorkspaceShell>
}
